server:
  num_threads: 1
  buffer_size: 64
  port: 8080
  grpc_port: 50051

log_level: INFO

models:
  - name: "squeezenet"
    path: "squeezenet1.0-8.onnx"
  - name: "maskrcnn"
    path: "MaskRCNN-10.onnx"
